#!/bin/sh

#status2d colors

black=#1e1e2e
lblack=#302d41
red=#F28FAD
lred=#E8A2AF
green=#ABE9B3
lgreen=#B5E8E0
yellow=#FAE3B0
lyellow=#F2CDCD
blue=#96CDFB
lblue=#89DCEB
magenta=#DDB6F2
lmagenta=#F5C2E7
lavender=#C9CBFF
rosewater=#F5E0DC
white=#D9E0EE
grey0=#575268
grey1=#6e6c7e
grey2=#988ba2
grey3=#c3bac6
