# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[](blue)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
format = "[]($style)[  $path](bg:#ddb6f2 fg:#1e1e2e bold)[ ]($style)"
style = "bg:#1e1e2e fg:#ddb6f2"

[git_branch]
format = "[]($style)[  $branch](bg:#f8bd96 fg:#1e1e2e bold)[ ]($style)"
style = "bg:#1e1e2e fg:#f8bd96"
