# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format="$directory$git_branch$character"
right_format="$cmd_duration"

# Prompt symbols 
[character]
success_symbol = "[](blue)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
format = "[ ](bg:#87b0f9)[   $path]($style)[ ](bg:#1e1e2e fg:#43465a)"
style = "bg:#43465a fg:#87b0f9"

[git_branch]
format = "[ ](bg:#f8bd96)[   $branch]($style)[ ](bg:#1e1e2e fg:#43465a)"
style = "bg:#43465a fg:#f8bd96"

[cmd_duration]
min_time = 1
format = "[](bg:#1e1e2e fg:#43465a)[  $duration ](fg:#f38ba8 bg:#43465a)[ ](bg:#f38ba8)"
